#!/bin/sh
#
# You need to configure vim to load .git/tags (or install Fugitive.vim).
#

EXCLUDE='--exclude=config --exclude=db --exclude=test --exclude=node_modules --exclude=public --exclude=webpack --exclude=script --exclude=app/assets --exclude=jenkins --exclude=vendor --exclude=coverage --exclude=package\*.json'

mkdir .git/tags_lock 2>/dev/null || exit 0
echo "Started ctags process..."

# universal-ctags - currently the best
(
  trap "rmdir .git/tags_lock; rm -f .git/tags.tmp" EXIT ;
  ctags -R --tag-relative=yes $EXCLUDE -f .git/tags.tmp ;
  mv .git/tags.tmp .git/tags
) &

# ripper-tags
#ripper-tags -R --force --tag-relative $EXCLUDE -f .git/tags.tmp || gem install ripper-tags 

# exuberant ctags
#ctags --tag-relative -R $EXCLUDE -f .git/tags.tmp

