#!/bin/bash
URL=${1:-http://localhost:3000}
CREDENTIALS=${2:-admin:admin}
REAL=${3:-dummy}
MAC1=$(echo -n 52:54:00:; openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//')
MAC2=$(echo -n 52:54:00:; openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//')
MAC3=$(echo -n 52:54:00:; openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//')
MAC4=$(echo -n 52:54:00:; openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//')
MACBMC=$(echo -n 52:54:00:; openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//')
IP1="10.$(($RANDOM % 250 + 1)).$(($RANDOM % 250 + 1)).$(($RANDOM % 250 + 2))"
IP2="192.168.122.$(($RANDOM % 250 + 2))"
IP3="10.$(($RANDOM % 250 + 1)).$(($RANDOM % 250 + 1)).$(($RANDOM % 250 + 2))"
IPBMC="10.$(($RANDOM % 250 + 1)).$(($RANDOM % 250 + 1)).$(($RANDOM % 250 + 2))"
TMP_DATA=$(mktemp /tmp/discover-host-XXXXXXXXXX)
#IP2="192.168.122.37"
#MAC2=52:54:00:01:02:03
DATE=$(date)
trap "rm -f $TMP_DATA" EXIT
cat <<EOD > $TMP_DATA
{
  "facts": {
    "discovery_version": "3.0.2",
    "interfaces": "fake1,fake2,fake3",
    "macaddress_fake1": "$MAC1",
    "macaddress_fake2": "$MAC2",
    "macaddress_fake3": "$MAC3",
    "ipaddress_fake1": "$IP1",
    "ipaddress_fake2": "$IP2",
    "ipaddress_fake3": "$IP3",
    "macaddress": "$MAC3",
    "ipaddress": "$IP3",
    "discovery_bootif": "$MAC2",
    "ipmi_enabled": "true",
    "ipmi_1_gateway": "10.1.1.1",
    "ipmi_1_ipaddress": "$IPBMC",
    "ipmi_1_ipaddress_source": "DHCP Address",
    "ipmi_1_macaddress": "$MACBMC",
    "ipmi_1_subnet_mask": "255.0.0.0",
    "ipmi_gateway": "10.1.1.1",
    "ipmi_ipaddress": "$IPBMC",
    "ipmi_ipaddress_source": "DHCP Address",
    "ipmi_macaddress": "$MACBMC",
    "ipmi_subnet_mask": "255.0.0.0",
    "physicalprocessorcount": "3",
    "memorysize_mb": "900",
    "blockdevice.sda_size": "1234567890",
    "blockdevice.sdb_size": "123456700",
    "Xforeman_organization": "TestOrg1",
    "Xforeman_location": "Olomouc",
    "discovery_test_a": "A",
    "discovery_test_b": "B",
    "hardwaremodel": "Fake Host FH420"
  }
}
EOD
[[ "$REAL" = "real" ]] && cat <<EOREAL > $TMP_DATA
{ "facts": {
  "sshrsakey": "AAAAB3NzaC1yc2EAAAADAQABAAABAQCmzbe87gYVtIMpK5EpsvTtZpkCRJrRCGOp1ejRgP9TbIjeq0C3m+1dc9nS4QUhQN1HtLAUjKkujefU/vIATv+i3s4kxPRm4HF0iaJIPC6j16eT53U4yYJS7eQV9JqqWyBQf4uofikU8SMhk/EbthwQseIpRZO2cAgmYeQ8PLKyk/Enn3UhLNua2ghqw0rVwYx9d0DDA98tx3nmjn8uIYP9qur4IPMhuM5FvRm6f3FmXxz83qHVMamvmsOcJT/0DuHyAicQltQXoHlEZVjT9y/CbBtQYNtprG1Fr9bBVhL0zNwN7L+gTyzMcW3PTpsEVxr38WL1hz+VVqj8+8SIKaNh",
  "sshfp_rsa": "SSHFP 1 1 f459b84028340badd2b6e8d6b70d3408ff281fb4\nSSHFP 1 2 790d2ddb04d2e52fa2aa0c941a75139ee4a823b8a08faad12890d20b4fa4b1c2",
  "sshecdsakey": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBQTBegA6e+kPCBLGKC2r6gWaQNzJaCao2/ciBvEVYIAlSefwct5CEWig7NDRw83C+jpiZV39O8BfQATuMU4myQ=",
  "sshfp_ecdsa": "SSHFP 3 1 3ca0b5fbc3ac20cbdb25aac3e12ecc431c2b5244\nSSHFP 3 2 2f6cc537d4230cda9e377ca6e7e73008533c08318fade032b60c36160a369765",
  "sshed25519key": "AAAAC3NzaC1lZDI1NTE5AAAAIAh61/NPFtOegohfpsoW2dwiVAbXvgu6zTudCEWF3sKX",
  "sshfp_ed25519": "SSHFP 4 1 572b9b7f4a38b8b9417bbf0686eb8c1aa1ad6c0a\nSSHFP 4 2 66ce93d710a922d6d345023d13fb6bc506515e22eaf3b13154f2365ed860bfe5",
  "architecture": "x86_64",
  "system_uptime": {
    "seconds": 38870,
    "hours": 10,
    "days": 0,
    "uptime": "10:47 hours"
  },
  "augeasversion": "1.1.0",
  "timezone": "EDT",
  "kernel": "Linux",
  "blockdevice_sda_size": 292326211584,
  "blockdevice_sda_vendor": "DELL",
  "blockdevice_sda_model": "PERC H700",
  "blockdevice_sr0_size": 1073741312,
  "blockdevice_sr0_vendor": "TEAC",
  "blockdevice_sr0_model": "DVD-ROM DV-28SW",
  "blockdevices": "sda,sr0",
  "dhcp_servers": {
    "system": "10.16.64.14",
    "em1": "10.16.64.14"
  },
  "domain": "rhts.eng.bos.redhat.com",
  "virtual": "physical",
  "is_virtual": false,
  "hardwaremodel": "x86_64",
  "operatingsystem": "RedHat",
  "os": {
    "name": "RedHat",
    "family": "RedHat",
    "release": {
      "major": "7",
      "minor": "1",
      "full": "7.1"
    },
    "lsb": {
      "distcodename": "Maipo",
      "distid": "RedHatEnterpriseServer",
      "distdescription": "Red Hat Enterprise Linux Server release 7.1 (Maipo)",
      "release": ":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch",
      "distrelease": "7.1",
      "majdistrelease": "7",
      "minordistrelease": "1"
    }
  },
  "facterversion": "2.4.1",
  "filesystems": "btrfs,ext2,ext3,ext4,msdos,vfat,xfs",
  "fqdn": "dell-per810-03.rhts.eng.bos.redhat.com",
  "gid": "root",
  "hardwareisa": "x86_64",
  "hostname": "dell-per810-03",
  "id": "root",
  "interfaces": "em1,em2,lo,virbr0,virbr1,virbr0_nic,virbr1_nic",
  "ipaddress_em1": "$IP1",
  "ipaddress6_em1": "2001:db8:1:0:225:64ff:fefa:9e0d",
  "macaddress_em1": "$MAC1",
  "netmask_em1": "255.255.248.0",
  "mtu_em1": 1500,
  "macaddress_em2": "$MAC2",
  "mtu_em2": 1500,
  "ipaddress_lo": "127.0.0.1",
  "netmask_lo": "255.0.0.0",
  "mtu_lo": 65536,
  "ipaddress_virbr0": "$IP2",
  "macaddress_virbr0": "$MAC3",
  "netmask_virbr0": "255.255.255.0",
  "mtu_virbr0": 1500,
  "ipaddress_virbr1": "$IP3",
  "macaddress_virbr1": "$MAC4",
  "netmask_virbr1": "255.255.255.0",
  "mtu_virbr1": 1500,
  "macaddress_virbr0_nic": "$MAC3",
  "mtu_virbr0_nic": 1500,
  "macaddress_virbr1_nic": "$MAC4",
  "mtu_virbr1_nic": 1500,
  "ipaddress": "$IP1",
  "discovery_bootif": "$MAC1",
  "ipaddress6": "2620:52:0:1040:225:64ff:fefa:9e0d",
  "kernelmajversion": "3.10",
  "kernelrelease": "3.10.0-229.el7.x86_64",
  "kernelversion": "3.10.0",
  "lsbdistcodename": "Maipo",
  "rubyplatform": "x86_64-linux",
  "lsbdistdescription": "Red Hat Enterprise Linux Server release 7.1 (Maipo)",
  "lsbdistid": "RedHatEnterpriseServer",
  "lsbdistrelease": "7.1",
  "lsbmajdistrelease": "7",
  "rubysitedir": "/usr/local/share/ruby/site_ruby/",
  "lsbminordistrelease": "1",
  "lsbrelease": ":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch",
  "macaddress": "$MAC1",
  "boardmanufacturer": "Dell Inc.",
  "boardproductname": "05W7DG",
  "boardserialnumber": "..CN7475101Q4576.",
  "bios_vendor": "Dell Inc.",
  "bios_version": "2.4.4",
  "bios_release_date": "08/12/2011",
  "manufacturer": "Dell Inc.",
  "productname": "PowerEdge R810",
  "serialnumber": "CZXKBM1",
  "uuid": "4C4C4544-005A-5810-804B-C3C04F424D31",
  "type": "Rack Mount Chassis",
  "memorysize": "31.24 GB",
  "memoryfree": "30.00 GB",
  "swapsize": "15.75 GB",
  "swapfree": "15.75 GB",
  "swapsize_mb": "16128.00",
  "swapfree_mb": "16128.00",
  "memorysize_mb": "31993.39",
  "memoryfree_mb": "30718.82",
  "netmask": "255.255.248.0",
  "network_em1": "10.16.64.0",
  "network_lo": "127.0.0.0",
  "network_virbr0": "192.168.122.0",
  "network_virbr1": "192.168.222.0",
  "operatingsystemmajrelease": "7",
  "rubyversion": "2.0.0",
  "operatingsystemrelease": "7.1",
  "osfamily": "RedHat",
  "partitions": {
    "sda1": {
      "uuid": "0c0dbfd1-3800-401d-8bc5-23147ed671c1",
      "size": "1024000",
      "mount": "/boot",
      "filesystem": "xfs"
    },
    "sda2": {
      "size": "569923584",
      "filesystem": "LVM2_member"
    }
  },
  "path": "/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin",
  "selinux": true,
  "selinux_enforced": true,
  "selinux_policyversion": "28",
  "selinux_current_mode": "enforcing",
  "selinux_config_mode": "enforcing",
  "selinux_config_policy": "unknown",
  "physicalprocessorcount": 2,
  "processors": {
    "models": [
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
      "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz"
    ],
    "count": 24,
    "physicalcount": 2
  },
  "processor0": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor1": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor2": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor3": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor4": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor5": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor6": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor7": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor8": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor9": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor10": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor11": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor12": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor13": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor14": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor15": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor16": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor17": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor18": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor19": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor20": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor21": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor22": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processor23": "Intel(R) Xeon(R) CPU           E7540  @ 2.00GHz",
  "processorcount": 24,
  "ps": "ps -ef",
  "puppetversion": "3.6.2",
  "uniqueid": "100a2e42",
  "uptime": "10:47 hours",
  "uptime_days": 0,
  "uptime_hours": 10,
  "uptime_seconds": 38870
}}
EOREAL
cat $TMP_DATA
curl -iku "$CREDENTIALS" \
  -H "Content-Type: application/json" \
  -d @$TMP_DATA -X POST $URL/api/v2/discovered_hosts/facts
echo -e "\n"
