#!/bin/bash
export PATH=/sbin:/usr/sbin:$PATH

usage() {
    echo "Usage: livecd-iso-to-pxeboot <isopath>"
    exit 1
}

cleanup() {
    [ -d "$STRIPPEDISO" ] && rm -rf $STRIPPEDISO
    [ -d "$CDMNT" ] && sudo umount $CDMNT && rmdir $CDMNT
}

cleanup_error() {
    echo "Cleaning up to exit..."
    cleanup
    exit 1
}

while [ $# -gt 1 ]; do
    case "$1" in
  *) usage ;;
    esac
    shift
done

ISO="$1"

if [ -z "$ISO" -o ! -e "$ISO" ]; then
    usage
fi

# Mount the ISO.
CDMNT=$(mktemp -d /tmp/$(basename $0)-mount.XXXXXX)
STRIPPEDISO=$(mktemp -d /tmp/$(basename $0)-stripped.XXXXXX)
sudo mount -o loop "$ISO" $CDMNT || cleanup_error

trap cleanup_error SIGINT SIGTERM
trap cleanup EXIT

# Does it look like an ISO?
if [[ ( ! -d $CDMNT/isolinux ) || ( ! -f $CDMNT/isolinux/initrd0.img && ! -f $CDMNT/isolinux/initrd.img  ) ]]; then
    echo "The ISO image doesn't look like a LiveCD ISO image to me."
    cleanup_error
fi

if [[ -f $CDMNT/isolinux/initrd0.img ]]; then
    INITRD=initrd0.img
    VMLINUZ=vmlinuz0
else
    INITRD=initrd.img
    VMLINUZ=vmlinuz
fi

NEWISO=$STRIPPEDISO/`basename "$ISO"`
genisoimage --quiet -J -joliet-long -r -T -o $NEWISO --root LiveOS $CDMNT/LiveOS/squashfs.img
( cd "$STRIPPEDISO" && ln -fs "$ISO" fdi.iso && echo fdi.iso | cpio -H newc --quiet -L -o ) |
  gzip -9 |
  cat $CDMNT/isolinux/$INITRD - > /var/lib/tftpboot/boot/fdi-image/$INITRD

# Kernel image.
cp -f $CDMNT/isolinux/$VMLINUZ /var/lib/tftpboot/boot/fdi-image/$VMLINUZ

exit 0
