#!/bin/env ruby
require 'foreman_api'
require 'logger'
require 'pry'

options = {
  :logger => Logger.new(STDOUT),
  :base_url => 'http://localhost:3000', 
  :username => 'admin', 
  :password => 'changeme'
}
klasses = ForemanApi::Resources.constants.select {|c| Class === ForemanApi::Resources.const_get(c)}
ForemanApi::Resources.constants.map { |klass| eval("#{klass.to_s} = ForemanApi::Resources::#{klass.to_s}.new(options)") }

puts "Available variables (resources):"
puts klasses.inspect
binding.pry
