#!/bin/bash

# Rebase & Merge & Push a remote branch using hub/git
[[ "$1" == "" ]] && echo "Usage: $0 pr_url" && exit 1
type hub >/dev/null || (echo "Hub tool is not installed, cannot continue!" && exit 2)

HUB_TOKEN=$(grep oauth_token ~/.config/hub | awk '{print $2}')
OWNER_REPO=$(echo "$1" | awk -F/ '{print $4 "/" $5}')
PRNUMBER=$(echo "$1" | awk -F/ '{print $7}')

blah() {
  echo -e "\e[1m$1\e[0m"
}

push_that() {
  git --no-pager log --graph --pretty=format:'%Cred%h%Creset %s %C(bold blue)<%an>%Creset' \
    --abbrev-commit "origin/$1..$1"
  echo -en "\n"
  blah "[*] SHOWING STATS"
  git diff "$PARENT..HEAD" --stat
  blah "[*] DRY-PUSHING"
  git push -n
  blah "[*] PUSH NOW FOR REAL [ENTER]?" && read && git push
  if [ "$?" == "0" ]; then
    LASTCOMMIT=$(git log | head -1 | cut -d ' ' -f2)
    curl --silent -X POST \
      -H "Content-Type: application/vnd.github.VERSION.raw+json" \
      -H "Authorization: token $HUB_TOKEN" \
      -d '{ "body" : "Merged as '"$LASTCOMMIT"', thank you!" }' "https://api.github.com/repos/$OWNER_REPO/issues/$PRNUMBER/comments"

    curl --silent -X PATCH \
      -H "Content-Type: application/vnd.github.VERSION.raw+json" \
      -H "Authorization: token $HUB_TOKEN" \
      -d '{ "state" : "closed" }' "https://api.github.com/repos/$OWNER_REPO/pulls/$PRNUMBER" > /dev/null
  fi
}

blah "[*] UPDATING"
git checkout develop 2>/dev/null || \
  git checkout master 2>/dev/null || \
  git checkout gh-pages 2>/dev/null
PARENT=$(git rev-parse --abbrev-ref HEAD)
blah "[*] PULLING $PARENT"
git pull
blah "[*] CHECKING OUT USING HUB"
hub checkout "$1" || git checkout "$1"
FROM=$(git rev-parse --abbrev-ref HEAD)
git checkout "$PARENT"
BRANCH=$(date +mff-temp-%Y%m%d-%H%M%S)
trap "git branch -D '$BRANCH'" EXIT
blah "[*] REBASE AND AMEND AND MERGE (IN BRANCH $BRANCH)"
git checkout -B "$BRANCH" "$FROM" && \
  git rebase -f "$PARENT" && \
  git diff "$PARENT..HEAD" --stat
echo "Spawning interactive shell. Feel free to rebase, merge, cherry-pick"
echo "and type 'exit' when done. The merging script will continue. You will"
echo "still able to cancel it before pushing to remote."
echo "The current HEAD is:"
git log -1
bash
git diff "$PARENT..HEAD"
git checkout "$PARENT" && git merge --ff-only "$BRANCH" && push_that "$PARENT"
# TODO https://github.com/stephencelis/ghi CLOSE PR
