#!/bin/bash

FROM_TAG=$1
TO_TAG=$2
KOJI_CMD="koji -c ~/.koji/katello-config"
DISTROS="rhel6 fedora18 fedora19"

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
  echo "Usage: $0 FROM_TAG TO_TAG PACKAGE_NAME"
  echo " "
  echo " Do not provide distribution suffixes for tags, it will automatically"
  echo " work with these: $DISTROS"
  echo " "
  echo "Example:"
  echo " $0 katello-thirdparty foreman-nightly rubygem-xyz [pkg2] ..."
  exit 1
fi

for PACKAGE in ${@:3}; do
  echo "Retagging $PACKAGE"
  for DIST in $DISTROS; do
    echo "Distro $DIST"
    LAST_BUILD=$($KOJI_CMD latest-build --quiet "$FROM_TAG-$DIST" "$PACKAGE" | awk '{print $1;}')
    if [ -z "$LAST_BUILD" ]; then
      echo "No build found in $FROM_TAG-$DIST"
    else
      echo "Tagging $LAST_BUILD into $TO_TAG-$DIST"
      $KOJI_CMD tag-build "$TO_TAG-$DIST" "$LAST_BUILD"
    fi
  done
done
