#!/bin/bash

if [ -z "$1" -o -z "$2" ]; then
  echo "Usage: $0 host tag"
  echo "Installs yum.repo with build root environment"
  echo " "
  echo "Example:"
  echo " $0 my_host foreman-nightly-rhel6"
  exit 1
fi

ssh "$1" "cat >/etc/yum.repos.d/$2.repo <<EOF
[$2]
name=$2
baseurl=http://koji.katello.org/repos/$2-build/latest/x86_64/
enabled=1
gpgcheck=0
EOF"

