#!/bin/bash

TAG1=$1
TAG2=$2
KOJI_CMD="koji -c ~/.koji/katello-config"

if [ -z "$1" -o -z "$2" ]; then
  echo "Usage: $0 TAG1 TAG2"; exit 1
fi

TEMPDIR=$(mktemp -d)
trap "rm -rf $TEMPDIR" EXIT

$KOJI_CMD list-tagged --quiet --latest $1 | awk '{print $1}' | sort > $TEMPDIR/$1
$KOJI_CMD list-tagged --quiet --latest $2 | awk '{print $1}' | sort > $TEMPDIR/$2

diff $TEMPDIR/$1 $TEMPDIR/$2
