#!/bin/sh
DEVICE='alsa_output.pci-0000_00_1b.0.analog-stereo'
ACTIVE_SINK=$(pacmd list-sinks | grep 'active port' | awk '{ print $3 }')

if [ "$ACTIVE_SINK" = "<analog-output-speaker>" ]; then
  WHAT=analog-output
  echo "[*] Enabling $WHAT on $DEVICE."
  pacmd set-sink-port $DEVICE $WHAT > /dev/null
else
  WHAT=analog-output-speaker
  echo "[*] Enabling $WHAT on $DEVICE."
  pacmd set-sink-port $DEVICE $WHAT > /dev/null
fi

exit 0
