#!/bin/bash

PROXYHOST=$(hostname)
PROXYPORT=8443
CERT=$HOME/.puppet/ssl/certs/$(hostname).pem
KEY=$HOME/.puppet/ssl/private_keys/$(hostname).pem
CACERT=$HOME/.puppet/ssl/certs/ca.pem
CREDENTIALS=admin:admin

curl -vsiku "$CREDENTIALS" \
  --cert $CERT --key $KEY --cacert $CACERT \
  -H "Content-Type: application/json" \
  https://$PROXYHOST:$PROXYPORT/$*
echo -e "\n"
