#!/bin/bash
#
# Send a scratchbuild from current directory.
#
# Usage: sbu [katello|fedora|hostname] [koji-tag] [dist-tag]
#

export LC_ALL=C
TARGET=${1:-katello}
KOJI_TAG=${2:-foreman-nightly-rhel6}
DIST=${3:-.el6}
[ ${DIST##.} = $DIST ] && DIST=.${DIST}
SRCDIR="$HOME/rpmbuild/SOURCES"

SPEC=$(ls *.spec | head -n1)
SPECDIR=$(pwd)
NAME=$(rpm -q --qf '%{NAME}\n' --specfile "$SPEC" | head -n1)
VERSION=$(rpm -q --qf '%{VERSION}\n' --specfile "$SPEC" | head -n1)
NAMEVERSION="$NAME-$VERSION"

echo "Working on $SPEC ($NAMEVERSION)"

# build SRPM
if spectool --list-files rubygem-foreman_discovery.spec | awk '{print $2}' | grep '^http'; then
  # sources are remote - download them first
  pushd $SRCDIR >/dev/null
  echo "Downloading sources..."
  spectool --list-files "$SPECDIR/$SPEC" | awk '{print $2}' | xargs -n 1 -P 4 wget -nc -c -q
  popd >/dev/null
  SRPM=$(rpmbuild -bs $NAME.spec --define "dist $DIST" | tail -n1 | sed 's/^Wrote: //g')
else
  # sources are most likely part of the git repo
  TEMPDIR=$(mktemp -d)
  trap "rm -rf $TEMPDIR" EXIT
  mkdir $TEMPDIR/$NAMEVERSION
  cp -Rad . $TEMPDIR/$NAMEVERSION
  pushd $TEMPDIR >/dev/null
  rm -rf `find -name ".git*"`
  tar c $NAMEVERSION | gzip -8 > ~/rpmbuild/SOURCES/$NAMEVERSION.tar.gz
  cd $NAMEVERSION
  SRPM=$(rpmbuild -bs $NAME.spec --define "dist $DIST" | tail -n1 | sed 's/^Wrote: //g')
  popd >/dev/null
fi

# submit the build
if [ "$TARGET" == "katello" ]; then
  koji -c ~/.koji/katello-config build --scratch --nowait $KOJI_TAG "$SRPM"
elif [ "$TARGET" == "katello-release" ]; then
  koji -c ~/.koji/katello-config build --nowait $KOJI_TAG "$SRPM"
elif [ "$TARGET" == "fedora" ]; then
  koji build --scratch --nowait $KOJI_TAG "$SRPM"
elif [ "$TARGET" == "fedora-release" ]; then
  koji build --nowait $KOJI_TAG "$SRPM"
else
  # local build on a hostname
  echo "Copying $SRPM to $TARGET"
  scp "$SRPM" "$TARGET:"
  SRPM_FILE=$(basename $SRPM)
  ssh -C "$TARGET" <<EOF
  RPMBUILD=~/rpmbuild
  echo Building $SRPM_FILE in \$RPMBUILD
  if [ -f "$SRPM_FILE" ]; then
    # install build essentials
    type -P gcc >/dev/null || yum groupinstall "Development Tools"

    # prepare and clean whole rpmbuild dir
    [ -d /usr/src/redhat/RPMS ] && RPMBUILD=/usr/src/redhat
    [ ! -x /usr/bin/rpmbuild -o ! -x /usr/bin/yum-builddep ] && yum -y install rpm-build yum-utils
    rm -rf \$RPMBUILD/*/*
    
    # install build deps and build (NOT using mock)
    echo "y" | yum-builddep "$SRPM_FILE"
    rpmbuild --rmsource --rmspec --rebuild "$SRPM_FILE" $2 $3 $4
    
    # remove headpin (we are testing only against katello)
    #rm -f \$RPMBUILD/*/*/*headpin*rpm

    # if fedora-review is enabled, do it now
    type -P fedora-review >/dev/null || yum -y install fedora-review
    fedora-review -n "$NAME" -r -p
   
    # install packages and if that fails try to --force it
    echo INSTALLING:
    ls \$RPMBUILD/*/*/*rpm
    # TODO - yum returns 0 on 'does not update installed package' error
    yum localinstall -y --nogpgcheck \$RPMBUILD/*/*/*rpm
    rpm -Uvh --oldpackage --force \$RPMBUILD/*/*/*rpm 2>&1
    echo DONE
  fi
EOF
fi
