#!/bin/bash
URL=${1:-http://localhost:3000}
CREDENTIALS=${2:-admin:admin}
HOSTNAME=${3:-$(hostname -f)}
TIME=$(date --rfc-3339=seconds --utc)
TMP_DATA=$(mktemp /tmp/send-report-XXXXXXXXXX)
trap "rm -f $TMP_DATA" EXIT
cat <<EOD > $TMP_DATA
{
  "report": {
    "host": "$HOSTNAME",
    "reported_at": "$TIME",
    "metrics": {},
    "status": {
      "applied": "0",
      "failed": "0",
      "failed_restarts": "0",
      "pending": "0",
      "restarted": "0",
      "skipped": "0"
    },
    "logs": [
      {
        "log": {
          "sources": {
            "source": "Puppet"
          },
          "messages": {
            "message": "Some weird Puppet error"
          },
          "level": "err"
        }
      },
      {
        "log": {
          "sources": {
            "source": "Puppet"
          },
          "messages": {
            "message": "Using cached catalog"
          },
          "level": "notice"
        }
      },
      {
        "log": {
          "sources": {
            "source": "Puppet"
          },
          "messages": {
            "message": "Could not retrieve catalog; skipping run"
          },
          "level": "err"
        }
      }
    ]
  }
}
EOD
cat $TMP_DATA
curl -iku "$CREDENTIALS" \
  -H "Content-Type: application/json" \
  -d @$TMP_DATA -X POST $URL/api/v2/reports/
echo -e "\n"
