#!/bin/bash
# yum -y install libxml2 yad
MAX=${1:-4}
echo "Fetching latest beaker results ..."
JOBS=$(bkr job-list --mine --format list | cut -d: -f2 | sort -n | tail -n $MAX)
TMP=/tmp/ssh-bkr
mkdir -p $TMP 2>/dev/null
SYSTEMS=()
for JOB in $JOBS; do
  echo "Parsing $JOB ..."
  JXML=$TMP/$JOB.xml
  [ -f $JXML ] || bkr job-results J:$JOB --prettyxml > $JXML
  R="'$(xmllint --xpath 'string(//job/recipeSet/recipe/@system)' $JXML)'"
  R+=" '$(xmllint --xpath '//job/whiteboard/text()' $JXML)'"
  R+=" '$(xmllint --xpath 'string(//job/@result)' $JXML)'"
  R+=" '$(xmllint --xpath 'string(//job/@status)' $JXML)'"
  SYSTEMS+=($R)
done

HOST=$(eval yad --list --column Hostname --column Whiteboard --column Status --column Result ${SYSTEMS[@]} | awk -F\| '{print $1}')

if [ ! -z "$HOST" ]; then
  echo "Connecting to $HOST ..."
  LC_ALL=en_US.utf8 ssh -o PasswordAuthentication=no root@$HOST
fi
