#!/usr/bin/env ruby
require 'net/http'
require 'uri'

def valid(url)
  uri = URI.parse(url)
  response = nil
  Net::HTTP.start(uri.host, uri.port) { |http|
    response = http.head(uri.path.size > 0 ? uri.path : "/")
  }
  return response.code == "200" || response.code == "302"
end

Dir["**/**"].select do |fn|
  next if File.directory?(fn)
  open(fn).each do |line|
    line.scan(/http:\/\/[\S]+/) do |url|
      begin
        puts url unless valid(url)
      rescue
        puts url
      end
    end
  end
end
