#!/bin/bash -x
NAME=$1
NEWNAME=$NAME-$(date '+%d%m%H%M')
BASEDEV=/dev/vg_virt/$NAME
NEWDEV=/dev/vg_virt/$NEWNAME
DOMAIN=${DOMAIN:-nat.lan}

sudo lvcreate -L9G -s -n $NEWNAME $BASEDEV
sudo virt-clone -o $NAME.$DOMAIN -n $NEWNAME -f $NEWDEV --preserve-data
sudo virsh start $NEWNAME
