#!/bin/bash
NAME=livecd
sudo virsh destroy $NAME
sudo virsh undefine $NAME

if [[ "$1" != "off" ]]; then
  sudo virt-install --os-variant rhel7 --vcpus 1 --ram 3900 \
    --name $NAME --nodisk \
    --cdrom /mnt/data/isos/foreman-live.iso \
    --graphics spice,listen=0.0.0.0 --noautoconsole &
  sleep 4
  virt-viewer -c qemu:///system $NAME &>/dev/null &
fi
