#!/bin/bash

_virsh()
{
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  names=$(sudo virsh list --all --name)

  _known_hosts
  COMPREPLY+=( $(compgen -W "${names}" -- ${cur}) )
  return 0
}

complete -F _virsh virsh
complete -F _virsh vm-start
complete -F _virsh vm-stop
complete -F _virsh vm-kill
complete -F _virsh ssh
